/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-01-04 01:57:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Collections;
import java.sql.*;
import java.util.Arrays;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 
           String name="nujsua";
           int age=12;
        
 int a=5;
        int b=10;
        int c=0;
        int d=8;
        
int swit=2;
 int n; int ilove=2; 
  int s=0,s1=0,toCheckValue,smax; int khu=0,khi=0,skhu=0,skhi=0;
             int []arr={3,1,2,7,9,8,10,6,5}; 
 Integer[] num = { 34,54,1,2,37}; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.Collections");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"nujsua.css\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleadd.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("<!--        <h1>Hello World!</h1>\n");
      out.write("         ");
      out.write("\n");
      out.write("        \n");
      out.write("        Name:");
      out.print( name );
      out.write("<br>\n");
      out.write("        Age:");
      out.print(age );
      out.write("\n");
      out.write("        ");

        out.println("</br>==========</br>");
        out.println("Age: "+age+"<br>");
        out.println("Name:"+name+"<br>");
        out.print("nujsua ua yog lawm");
        
      out.write("<hr>\n");
      out.write("        \n");
      out.write("       <br>\n");
      out.write("       <h4>hau no yog 11/9/2020</h4>\n");
      out.write("        \n");
      out.write("        ");
      out.write("\n");
      out.write("        ");
 c=a+b; 
      out.write("\n");
      out.write("        ");
      out.print( c );
      out.write("<br>\n");
      out.write("        ");
      out.print( a<b );
      out.write("<br>\n");
      out.write("        ");
      out.print( !(a>b) );
      out.write("<br>\n");
      out.write("        ");
 out.println((a<b)&&(b>d)); 
      out.write("<br>\n");
      out.write("        ");
 out.println((a<b)||(b>d)); 
      out.write("<br>\n");
      out.write("        <hr> comment \n");
      out.write("        <p>haun nos yog hnub kuv siv ua form tawm jas</p>\n");
      out.write("<hr>\n");
      out.write("        <p>hau no yog hnub tim 16/11/2020</p>\n");
      out.write("        ");
      out.write("\n");
      out.write("            ");
 
                switch (swit){
                    case 1:
                        out.println("nuj1");
                        break;
                    case 2:
                        out.println("nuj2");
                        break;
                    case 3:
                        out.println("nuj3");
                        break;
                    case 4:
                        out.println("nuj4");
                        break; 
                        
                }
            
      out.write("\n");
      out.write("            <hr>\n");
      out.write("            <p>Hauv qab no yog hnub tim 23/10/2020</p>\n");
      out.write("            <form action=\"data.jsp\" method=\"GET\">\n");
      out.write("                <p>A:<input type=\"text\" name=\"text1\" value=\"\"><br></p>\n");
      out.write("                <p>B:<input type=\"text\" name=\"text2\" value=\"\"><br></p>  \n");
      out.write("                <button type=\"submit\">Go!</button>\n");
      out.write("                \n");
      out.write("            </form>-->\n");
      out.write("<!--           <form  action=\"data.jsp\" method=\"post\">\n");
      out.write("                <p>Name:<input type=\"text\" name=\"Name\" value=\"\"></p>\n");
      out.write("                <p>Last Name:<input type=\"text\" name=\"Lane\"value=\"\"></p>\n");
      out.write("                <label><input type=\"radio\" name=\"women\" value=\"women\">women</label>\n");
      out.write("                <label><input type=\"radio\" name=\"women\"j value=\"man\">man </label>\n");
      out.write("                <br>\n");
      out.write("                <select name=\"xais\">\n");
      out.write("                        <option value=\"python\">python</option>\n");
      out.write("                        <option value=\"c#\">c#</option>\n");
      out.write("                </select>\n");
      out.write("                <br>\n");
      out.write("                <label><input type=\"checkbox\" value=\"Mean\" name=\"option\">mean</label>\n");
      out.write("                <label><input type=\"checkbox\" value=\"php\" name=\"option\">php</label>\n");
      out.write("                <label><input type=\"checkbox\" value=\"asp.net\" name=\"option\"> asp</label>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <textarea name=\"conmen\" rows=\"5\" cols=\"25\" value=\"\"></textarea>\n");
      out.write("                    <p>A:<input type=\"text\" name=\"text1\" value=\"0\"><br></p>\n");
      out.write("                    <p>B:<input type=\"text\" name=\"text2\" value=\"0\"><br></p>\n");
      out.write("                </div>\n");
      out.write("            <button type=\"submit\"> GO!</button>\n");
      out.write("        </form>-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--<table style=\"width:100%\">\n");
      out.write("  <tr>\n");
      out.write("      <th rowspan=\"\">ປະເພດສິນຄ້າ</th>\n");
      out.write("      <th colspan=\"3\">ລາຍການສິນຄ້າ</th>\n");
      out.write("    \n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("        <td rowspan=\"4\">ເຄື່ອງສຳອາງ</td>\n");
      out.write("        <td></td>\n");
      out.write("        <td></td>\n");
      out.write("        <td></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td></td>\n");
      out.write("    <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("      <td></td>\n");
      out.write("      <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("    <tr>\n");
      out.write("     <td></td>\n");
      out.write("      <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("      <tr>\n");
      out.write("          <td rowspan=\"4\">ເຄື່ອງດື່ມ</td>\n");
      out.write("      <td></td>\n");
      out.write("    <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("     <td></td>\n");
      out.write("      <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("     <td></td>\n");
      out.write("      <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("   <tr>\n");
      out.write("    <td></td>\n");
      out.write("    <td></td>\n");
      out.write("    <td></td>\n");
      out.write("  </tr>\n");
      out.write("</table>-->\n");
      out.write("\n");
      out.write("<!--                ");
      out.write("\n");
      out.write("                ");

                String strn = request.getParameter("textnumber");
                if(strn !=null){
                    n =Integer.parseInt(strn);
                }
                
      out.write("\n");
      out.write("           <table width=\"80%\" border=\"1\" align=\"center\"><br>\n");
      out.write("\n");
      out.write("                <tr align=\"center\">\n");
      out.write("                    <th>ລໍາດັບ</th>\n");
      out.write("                    <th>ຊື່</th>\n");
      out.write("                    <th>ນາມສະກຸນ່</th>\n");
      out.write("                    <th>ເບີໂທລະສັບ</th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>1</td>\n");
      out.write("                    <td>nujsua</td>\n");
      out.write("                    <td>hwj</td>\n");
      out.write("                    <td>02091826096</td>\n");
      out.write("                </tr>\n");
      out.write("                ");

                    for(int i=0;i<n;i++){

               
      out.write("\n");
      out.write("                 <tr>\n");
      out.write("                       <td>");
      out.print(ilove );
      out.write("</td>\n");
      out.write("                       <td></td>\n");
      out.write("                       <td></td>\n");
      out.write("                       <td></td>\n");
      out.write("                 </tr>\n");
      out.write("\n");
      out.write("                ");

                   ilove++;
             }
                
      out.write("\n");
      out.write("            <br>\n");
      out.write("            <form align=\"center\">\n");
      out.write("            <input type=\"text\" name=\"textnumber\">\n");
      out.write("            <input type=\"submit\" name=\"sbm\" value=\"enter\"><br>\n");
      out.write("            </form>-->\n");
      out.write("                \n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
 
                 Connection connection = null;
        try {
        Class.forName("com.mysql.jdbc.Driver"); 
        connection = DriverManager.getConnection("jdbc:mysql://localhost/xyovlistiag"+
                            "?user=root && password=");
        if(connection !=null){
            out.println("zoo lawm");
        }else {
            out.println("connect tsis tau thaib");
        }
        }catch(Exception ex){
        out.println("connect tsis tau");
        ex.printStackTrace();
        }
        
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        \n");
      out.write("       ");
 
           out.println("<p>nyob tsis zoo</p>");
        for( int i=0;i<arr.length;i++){
       out.println(arr[i]);
       s+=arr[i];
       if(arr[i]%2==0){
           khu+=1;
           skhu+=arr[i];
       }else{
           khi+=1;
           skhi+=arr[i];
           
       }
        }
        out.println("<br>");
        out.println(s);
        out.println("<br>"+khu);
         out.println("<br>"+khi);
          out.println("<br>"+skhu);
           out.println("<br>"+skhi);
       
      out.write("\n");
      out.write("       \n");
      out.write("       ");
 
            for(int n :arr){
                s1+=n;
            }
            out.println("<br>"+s1+"<br>");
       
      out.write("\n");
      out.write("       \n");
      out.write("       ");
      out.write("\n");
      out.write("       ");
 
          int min = Collections.min(Arrays.asList(num));
            int max = Collections.max(Arrays.asList(num));
             out.println("array is =>");
            for( int i=0;i<num.length;i++){
            out.println(arr[i]);
            smax+=num[i];
             }
       
      out.write("\n");
      out.write("       <br>\n");
      out.write("       ");

            out.println("Minimum number of array is : "+ min+"<br>");
            out.println("Maximum number of array is : " + max);
           
      out.write("\n");
      out.write("        \n");
      out.write("           \n");
      out.write("           \n");
      out.write("           \n");
      out.write("           \n");
      out.write("           \n");
      out.write("           \n");
      out.write("       \n");
      out.write("    \n");
      out.write("            \n");
      out.write("            \n");
      out.write("        <script src=\"scriptadd.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
